// 상품 리스트
export const SHOPPING_LIST = [
  {
    id: 1,
    category: "stationery",
    image: "./images/note.jpg",
    name: "잔망루피 페이스 스프링 노트",
    price: 4000,
    liked: false,
  },
  {
    id: 2,
    category: "stationery",
    image: "./images/bag.jpg",
    name: "잔망루피 쇼핑백 (2종/택1)",
    price: 1500,
    liked: false,
  },
  {
    id: 3,
    category: "stationery",
    image: "./images/sticker.jpg",
    name: "잔망루피 스티커",
    price: 1500,
    liked: false,
  },
  {
    id: 4,
    category: "fashion",
    image: "./images/doll.jpg",
    name: "잔망루피 파자마 봉제 인형",
    price: 29000,
    liked: false,
  },
  {
    id: 5,
    category: "fashion",
    image: "./images/passport.jpg",
    name: "잔망루피 여권 케이스",
    price: 5900,
    liked: false,
  },
  {
    id: 6,
    category: "fashion",
    image: "./images/flower.jpg",
    name: "잔망루피 꽃다발 봉제 인형",
    price: 34000,
    liked: false,
  },
  {
    id: 7,
    category: "digital",
    image: "./images/mouse.jpg",
    name: "잔망루피 마우스패드",
    price: 4000,
    liked: false,
  },
  {
    id: 8,
    category: "digital",
    image: "./images/usb.jpg",
    name: "로이체 잔망루피 5in1 멀티 USB 허브",
    price: 36900,
    liked: false,
  },
  {
    id: 9,
    category: "digital",
    image: "./images/mic.jpg",
    name: "로이체 잔망루피 블루투스 마이크 스피커",
    price: 39900,
    liked: false,
  },
];
